Multy-io/Multy-Android

app/src/main/java/io/multy/fcm/MultyFirebaseMessagingService.java
app/src/main/java/io/multy/storage/AssetsDao.java
app/src/main/java/io/multy/ui/activities/AssetActivity.java
app/src/main/java/io/multy/ui/activities/BaseActivity.java
app/src/main/java/io/multy/ui/activities/MainActivity.java
app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java
app/src/main/java/io/multy/ui/fragments/asset/EthTransactionInfoFragment.java
app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java
app/src/main/java/io/multy/ui/fragments/main/SettingsFragment.java
app/src/main/java/io/multy/util/Constants.java
app/src/main/java/io/multy/viewmodels/WalletViewModel.java
app/src/main/res/layout/fragment_eth_transaction_info.xml
app/src/main/res/layout/fragment_transaction_info.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml
build.gradle

MUL-1641 Pushes. Settings and navigation

---

app/src/main/java/io/multy/ui/activities/AssetActivity.java

Bugfix - eth transaction info fix

---

app/src/main/java/io/multy/ui/fragments/dialogs/ContactDialog.java
app/src/main/java/io/multy/ui/fragments/main/contacts/ContactsFragment.java
app/src/main/java/io/multy/ui/fragments/send/AssetSendFragment.java
app/src/main/res/layout/activity_asset_send.xml
app/src/main/res/layout/bottom_sheet_address_actions.xml
app/src/main/res/layout/fragment_contacts.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

Bugfix - Contacts send screen fix

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/multy/Multy.java
app/src/main/java/io/multy/service/SyncService.java
app/src/main/java/io/multy/storage/SettingsDao.java
app/src/main/java/io/multy/ui/adapters/ContactAdapter.java
app/src/main/java/io/multy/ui/fragments/dialogs/AddressActionsDialogFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/ContactDialog.java
app/src/main/java/io/multy/ui/fragments/main/contacts/ContactInfoFragment.java
app/src/main/java/io/multy/ui/fragments/main/contacts/ContactsFragment.java
app/src/main/java/io/multy/util/ContactUtils.java
app/src/main/java/io/multy/util/analytics/Analytics.java
app/src/main/java/io/multy/util/analytics/AnalyticsConstants.java
app/src/main/res/layout/bottom_sheet_contact_dialog.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

MUL-1651- Implement contacts.

---

app/build.gradle
app/src/main/java/io/multy/storage/SettingsDao.java
app/src/main/java/io/multy/ui/activities/AssetRequestActivity.java
app/src/main/java/io/multy/ui/adapters/ContactAdapter.java
app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/AddressActionsDialogFragment.java
app/src/main/java/io/multy/ui/fragments/main/contacts/ContactsFragment.java
app/src/main/java/io/multy/ui/fragments/send/WalletChooserFragment.java
app/src/main/java/io/multy/util/Constants.java
app/src/main/java/io/multy/util/ContactUtils.java
app/src/main/res/xml/authenticator.xml
app/src/main/res/xml/sync_adapter.xml

Contacts bugfix

---

app/src/main/java/io/multy/ui/fragments/send/ethereum/EthAmountChooserFragment.java

bugfix total sum of eth choose amount

---

app/src/main/java/io/multy/fcm/MultyFirebaseMessagingService.java
app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java
app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java
app/src/main/java/io/multy/viewmodels/WalletViewModel.java

bugfix wallet creation

---

app/src/main/java/io/multy/ui/activities/DonationActivity.java
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

improved localization

---

app/build.gradle
app/src/main/java/io/multy/api/ApiServiceInterface.java
app/src/main/java/io/multy/api/MultyApi.java
app/src/main/java/io/multy/api/MultyApiInterface.java
app/src/main/java/io/multy/model/requests/CreateMultisigRequest.java
app/src/main/java/io/multy/ui/activities/CreateAssetActivity.java
app/src/main/java/io/multy/ui/adapters/MyWalletsAdapter.java
app/src/main/java/io/multy/ui/fragments/BaseFragment.java
app/src/main/java/io/multy/ui/fragments/asset/CreateMultisigBlankFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/AssetActionsDialogFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/ChooseMembersDialog.java
app/src/main/java/io/multy/ui/fragments/dialogs/WalletChooserDialogFragment.java
app/src/main/java/io/multy/util/Constants.java
app/src/main/java/io/multy/viewmodels/BaseViewModel.java
app/src/main/res/drawable/background_choose_members.xml
app/src/main/res/drawable/ic_wallet_create_new_multisig.xml
app/src/main/res/drawable/ic_wallet_join_multisig.xml
app/src/main/res/layout/bottom_sheet_choose_members.xml
app/src/main/res/layout/bottom_sheet_wallet_action.xml
app/src/main/res/layout/fragment_create_multisig_blank.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

MUL-1777 Create ETH multisig screen

---

app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java

merge only after back-end will be updated from stage

MUL-1695 Review response of create asset 

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/multy/ui/activities/CreateAssetActivity.java
app/src/main/java/io/multy/ui/adapters/MyWalletsAdapter.java
app/src/main/java/io/multy/ui/fragments/ScanInvitationCodeFragment.java
app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/AssetActionsDialogFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/WalletChooserDialogFragment.java
app/src/main/java/io/multy/util/Constants.java
app/src/main/res/drawable/background_gradient_dark.xml
app/src/main/res/drawable/ic_qr_icon_white.xml
app/src/main/res/layout/fragment_scan_invite_code.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

MUL-1778 Scan invite code screen for MS

---

app/src/main/cpp/scratch.cpp
app/src/main/java/io/multy/model/entities/wallet/Wallet.java
app/src/main/java/io/multy/ui/activities/AssetRequestActivity.java
app/src/main/java/io/multy/ui/activities/MagicSendActivity.java
app/src/main/java/io/multy/ui/activities/MainActivity.java
app/src/main/java/io/multy/ui/adapters/AssetTransactionsAdapter.java
app/src/main/java/io/multy/ui/adapters/MyWalletPagerAdapter.java
app/src/main/java/io/multy/ui/adapters/MyWalletsAdapter.java
app/src/main/java/io/multy/ui/adapters/RecentAddressesAdapter.java
app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java
app/src/main/java/io/multy/ui/fragments/asset/EthTransactionInfoFragment.java
app/src/main/java/io/multy/ui/fragments/asset/TransactionInfoFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/CompleteDialogFragment.java
app/src/main/java/io/multy/ui/fragments/main/AssetsFragment.java
app/src/main/java/io/multy/ui/fragments/receive/RequestSummaryFragment.java
app/src/main/java/io/multy/ui/fragments/seed/SeedValidationFragment.java
app/src/main/java/io/multy/ui/fragments/send/AssetSendFragment.java
app/src/main/java/io/multy/util/CryptoFormatUtils.java
app/src/main/java/io/multy/util/JniException.java
app/src/main/java/io/multy/viewmodels/AssetRequestViewModel.java
app/src/main/java/io/multy/viewmodels/WalletViewModel.java
app/src/main/res/drawable/ic_restore_multy.xml
app/src/main/res/layout/first_launch_create_restore.xml
app/src/main/res/layout/fragment_contacts.xml
app/src/main/res/layout/view_transaction_item.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

MUL-1872-Crashlytics

---

app/src/main/java/io/multy/ui/activities/CreateMultiSigActivity.java
app/src/main/java/io/multy/ui/adapters/EthTransactionsAdapter.java
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

MUL-1935-MS: factory address fix

---

app/src/main/java/io/multy/Multy.java
app/src/main/java/io/multy/ui/fragments/MagicReceiveFragment.java
app/src/main/java/io/multy/util/MultyRealmMigration.java

MUL-1928-migration

---

app/src/main/java/io/multy/storage/AssetsDao.java
app/src/main/java/io/multy/ui/adapters/EthTransactionsAdapter.java
app/src/main/java/io/multy/ui/adapters/MultisigOwnersAdapter.java
app/src/main/java/io/multy/viewmodels/WalletViewModel.java
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

MUL-1935-MS

---

app/build.gradle
app/src/main/java/io/multy/ui/MyWebView.java
app/src/main/java/io/multy/ui/activities/CreateMultiSigActivity.java
app/src/main/java/io/multy/ui/fragments/Web3Fragment.java
app/src/main/java/io/multy/ui/fragments/asset/CreateMultisigBlankFragment.java
app/src/main/res/layout/fragment_web_dapps.xml

dynamic price of MS creation
crashes fix
error handling

release bug fix

---

app/src/main/java/io/multy/ui/activities/CreateMultiSigActivity.java
app/src/main/java/io/multy/ui/activities/ImportEthWalletActivity.java
app/src/main/java/io/multy/ui/activities/ImportMultisigActivity.java
app/src/main/java/io/multy/ui/activities/MagicSendActivity.java
app/src/main/java/io/multy/ui/activities/MainActivity.java
app/src/main/java/io/multy/ui/activities/SplashActivity.java
app/src/main/java/io/multy/ui/adapters/RecentAddressesAdapter.java
app/src/main/java/io/multy/ui/fragments/AddressesFragment.java
app/src/main/java/io/multy/ui/fragments/asset/AssetInfoFragment.java
app/src/main/java/io/multy/ui/fragments/asset/CreateAssetFragment.java
app/src/main/java/io/multy/ui/fragments/dialogs/PrivateKeyDialogFragment.java
app/src/main/java/io/multy/ui/fragments/send/AmountChooserFragment.java
app/src/main/java/io/multy/ui/fragments/send/SendSummaryFragment.java
app/src/main/java/io/multy/ui/fragments/send/WalletChooserFragment.java
app/src/main/java/io/multy/ui/fragments/send/ethereum/EthAmountChooserFragment.java
app/src/main/java/io/multy/ui/fragments/send/ethereum/EthSendSummaryFragment.java
app/src/main/java/io/multy/util/Constants.java
app/src/main/java/io/multy/util/DeepLinkShareHelper.java
app/src/main/java/io/multy/util/MultyRealmMigration.java
app/src/main/java/io/multy/viewmodels/AssetSendViewModel.java
app/src/main/java/io/multy/viewmodels/WalletViewModel.java
app/src/main/res/layout/activity_import_eth.xml
app/src/main/res/layout/activity_import_multisig.xml
app/src/main/res/layout/fragment_asset_settings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-uk/strings.xml
app/src/main/res/values/strings.xml

Mul-1922 send from import - bugfix

---

app/src/main/java/io/multy/ui/activities/MainActivity.java
app/src/main/java/io/multy/ui/activities/SplashActivity.java
app/src/main/java/io/multy/ui/fragments/main/FeedFragment.java
app/src/main/java/io/multy/util/Constants.java

parsing dragons deep link

---

app/src/main/cpp/scratch.cpp

MUL-1907: Refactor android scratch.cpp from C pointer to smart pointer

MUL-1907: Refactor android scratch.cpp from C pointer to smart pointer

---

app/src/main/java/io/multy/model/entities/Fee.java
app/src/main/java/io/multy/ui/adapters/MyFeeAdapter.java
app/src/main/java/io/multy/ui/fragments/DonationFragment.java
app/src/main/java/io/multy/ui/fragments/send/TransactionFeeFragment.java
app/src/main/java/io/multy/ui/fragments/send/ethereum/EthTransactionFeeFragment.java
app/src/main/java/io/multy/viewmodels/AssetSendViewModel.java
app/src/main/res/layout/dialog_custom_eth_fee.xml

Send ETH transaction need to be tested.

added gas limit selection. 
